# DocumentDB
spring.data.mongodb.uri=mongodb://docdbadmin:4475Bc899266@write-to-docdb.cluster-cytxdqtguo9f.ap-south-1.docdb.amazonaws.com:27017/mystepfunctiondocdb?tls=true&tlsCAFile=/app/global-bundle.pem&replicaSet=rs0&retryWrites=false

spring.batch.job.enabled=true
spring.batch.job.name=mongoRecordProcessingJob

logging.level.org.springframework.batch=INFO
logging.level.com.example.batchdemo=INFO

# AWS Region
aws.region=ap-south-1
aws.s3.bucket-name=step-function-ecs-batch-processing
aws.s3.input-key=csv/sample_1000_records_with_recordType.csv
chunk.bucket.name=step-function-ecs-batch-processing
spring.main.web-application-type=none