
spring.datasource.url=jdbc:mysql://localhost:3306/batch_demo2
spring.datasource.username=root
spring.datasource.password=21311a1988
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.datasource.url=jdbc:postgresql://database-2.cluster-cutcwscqwez3.us-east-1.rds.amazonaws.com:5432/postgres?sslmode=require
#spring.datasource.username=postgres
#spring.datasource.password=database-2.cluster-cutcwscqwez3.us-east-1.rds.amazonaws.com:5432/?Action=connect&DBUser=postgres&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAXBJVUBDDPKSXOQNR%2F20260914%2Fus-east-1%2Frds-db%2Faws4_request&X-Amz-Date=20260914T104641Z&X-Amz-Expires=900&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEBsaCXVzLWVhc3QtMSJHMEUCIEB9f%2B1SCv8JFrTXc%2Bn4KpAGMoUjJ%2B8tKJ%2BOKOj1wqe9AiEAswW6%2B0hu0eMaGrx5bAS0gu8QrEqaTgzIBz1V8kWEvnIq4QII5P%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgw0ODM4MzMxNTM3MzQiDIR07S%2FnK8cb4wUbdiq1AveZz9oJ3RVWzKaTFY1TKufV933oFYME2WBQ72iLys4q0ES6SRfKebmpz%2FaNkinSOCpJnGUBNC5fxx3M3QnRoSTSMp19eYXtZ5D%2Fx2t2kgAE8FliIL97%2BmqVCQz1F2GUduEJofd1dPNqni1FzE3PKcSghsO6zpdi3BJirdX0u7Wyko8PuIZjTSzaaQofp1rHndk8JZkfMDr3RvUn5F%2BaQxdQeZmsaUQfP13DC4hhqBhJv0dpVje%2F5w19yFX1%2BN%2B5pqBGS2KZIAuyJNbfdn83Jt3xTFwXgVKp%2FdVmOTHevKNOq%2BlfkwUXGKjvP%2BkdL6kw7fv5aBI3mJIEtNzl8w%2FBJm7dsSQsVR6Z0DJIZFKHUP0ODf%2BFZSMbRkGUQsM8JsInVnCUnhaDeUfBWUez2X4iLv%2FtD23LiTCAgp%2FVBjqtAp4LKNgL1utPN43SzHvdCDja%2Fzzw8OxFOlzRce7cIB9gc57XnE%2FFId4ens8tIVV6rWFUFjl4Bzi%2FneO8%2FRdCPueXPzo7EYOTImZUxJT05zk%2FexsYSclWtiAImP3VdSryh7ylbWZIBjYWz1w0CdxE0x3VhrK6zaNyOqaLfXecStVpdbjVfivaVks0cUPZPxqO%2BbACBRJQTWl5M%2FbBrDsptK%2F4asKvunQXP7dkqEgUEzF5vaPHZ4qfHOwEyEjxmkIOGCfVfsmrwqoRd5j5XBJUoSW7GtpPXh1N4f7AteI9zZm8r3AcYYBaurQ4gPCjnT4TkK9MHtnY5yToo7Hn6OsDc7hUm%2Fh%2B9LSVSm9TPhl2Vif9GAI8VRhZ22meuJCogpMH2S4dUO7LWu25s9QUs4g%3D&X-Amz-Signature=a10d59d34f47d06eea4be7f4dc4a76b1179cd177547e8bf4d7b602de1f1f3872&X-Amz-SignedHeaders=host
#spring.datasource.driver-class-name=org.postgresql.Driver
# DocumentDB

spring.data.mongodb.uri=mongodb://docdbadmin:4475Bc899266@write-to-docdb.cluster-cytxdqtguo9f.ap-south-1.docdb.amazonaws.com:27017/mystepfunctiondocdb?tls=true&tlsCAFile=/app/global-bundle.pem&replicaSet=rs0&retryWrites=false

spring.batch.job.enabled=true
spring.batch.jdbc.initialize-schema=always
spring.batch.job.name=mongoRecordProcessingJob

logging.level.org.springframework.batch=INFO
logging.level.com.example.batchdemo=INFO

# AWS Region

aws.region=ap-south-1
aws.s3.bucket-name=step-function-ecs-batch-processing
aws.s3.input-key=csv/sample_1000_records_with_recordType.csv
chunk.bucket.name=step-function-ecs-batch-processing